spring:
  application:
    name: auth-service
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_test_db
    username: ${DB_USERNAME:test_user}
    password: ${DB_PASSWORD:test_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/

server:
  port: 8081

app:
  jwt:
    secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLong!!!}
    expiration: 900000  # 15 minutes
    refresh-expiration: 604800000 # 7 days
