version: '3.8'
services:
  postgres-test:
    image: postgres:15-alpine
    container_name: auth-service-test-db
    environment:
      POSTGRES_DB: auth_test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d auth_test_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:
